# -*- coding: utf-8 -*-
"""
ArcPy helper functions used in preprocessing (Proglacial_project.py).

Functions
---------
select_area_shp   -- Extract a single study area polygon to its own shapefile
clip_s2           -- Clip an S2 band to the study area and create a 10 m fishnet
reproject_s2      -- Reproject an S2 raster to SWEREF99 TM (EPSG:3006)
clip_ortho        -- Clip the full orthophoto (all bands) to the study area
clip_ortho_band   -- Aggregate one ortho band to 10 m via zonal statistics, then clip
create_mask       -- Build a pixel quality mask (snow / water / shadow / brightness)
band_correlation  -- Run OLS between normalised ortho and S2 band values

All rasters are written to C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\

Requires: arcpy (ArcGIS Pro, Spatial Analyst + Image Analyst + 3D extensions)
Generated by ArcGIS ModelBuilder on : 2025-11-16 19:10:19
Corrected to use Map Algebra instead of RasterCalculator
"""
import arcpy
from arcpy.ia import *
from arcpy.sa import *


def select_area_shp(area_name, shp_path):
    """
    Extract a single glacier's polygon from the master shapefile.

    Uses an attribute query on 'Glacier_na' to isolate one study area,
    saving it as a standalone shapefile that can be used as a mask in
    subsequent ArcPy spatial operations.

    Parameters
    ----------
    area_name : str  Name of the glacier (must match 'Glacier_na' field)
    shp_path  : str  Path to the master proglacial outlines shapefile

    Returns
    -------
    str  Path to the single-area output shapefile
    """
    area_name_select_shp = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_select.shp"
    arcpy.analysis.Select(in_features=shp_path, out_feature_class=area_name_select_shp, where_clause=f"Glacier_na = '{area_name}'")
    return area_name_select_shp


def clip_s2(area_name, s2_reprojected_path, band_name, area_shp):
    """
    Clip a reprojected S2 band to the study area and generate a 10 m fishnet.

    The fishnet is a grid of polygons whose cells exactly align with S2 pixels.
    It is used later as zonal zones when aggregating high-resolution ortho bands
    to 10 m, ensuring spatial alignment between S2 and ortho-derived statistics.

    Parameters
    ----------
    area_name          : str  Glacier name
    s2_reprojected_path: str  Path to the already-reprojected S2 raster
    band_name          : str  S2 band identifier (e.g. 's2_b8')
    area_shp           : str  Path to the single-area mask shapefile

    Returns
    -------
    tuple  (clipped_raster_path, fishnet_shapefile_path)
    """
    _area_name_S2_band_clip_tif = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{band_name}_clip.tif"
    Extract_by_Mask_2_ = _area_name_S2_band_clip_tif
    # ExtractByMask clips to the exact polygon boundary
    _area_name_S2_band_clip_tif = arcpy.sa.ExtractByMask(s2_reprojected_path, area_shp, "INSIDE")
    _area_name_S2_band_clip_tif.save(Extract_by_Mask_2_)

    # Derive fishnet extent from the clipped raster's bounding box
    clip_raster = arcpy.Raster(_area_name_S2_band_clip_tif)
    extent = clip_raster.extent

    # Origin and Y-axis define the coordinate reference for the fishnet
    origin_coord = f"{extent.XMin} {extent.YMin}"
    y_axis_coord = f"{extent.XMin} {extent.YMax}"

    # Create a polygon grid with 10 m x 10 m cells matching S2 pixel footprints
    _area_name_S2_band_fishnet_shp = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{band_name}_fishnet.shp"
    Output_Label_Feature_Class = arcpy.management.CreateFishnet(origin_coord=origin_coord, y_axis_coord=y_axis_coord, out_feature_class=_area_name_S2_band_fishnet_shp, cell_width=10, cell_height=10, number_rows=None, number_columns=None, labels="NO_LABELS", template=_area_name_S2_band_clip_tif, geometry_type="POLYGON")[0]

    return _area_name_S2_band_clip_tif, _area_name_S2_band_fishnet_shp


def reproject_s2(s2_band_path, index, band_name):
    """
    Reproject a Sentinel-2 band to SWEREF99 TM (EPSG:3006).

    S2 imagery is delivered in UTM; this step converts it to the Swedish
    national grid so it aligns with the orthophotos and LiDAR DEM.
    Bilinear resampling preserves continuity of spectral values.

    Parameters
    ----------
    s2_band_path : str  Path to the original S2 raster
    index        : int  Sequential index used to name the output file uniquely
    band_name    : str  S2 band identifier (used in output filename)

    Returns
    -------
    arcpy.Raster  Reprojected raster object
    """
    S2_band = Raster(s2_band_path)
    _area_name_S2_band_reproject_tif = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\s2_reprojections\\{band_name}_{index}_reproject.tif"
    # Full WKT for SWEREF99 TM ensures exact CRS match with other data sources
    arcpy.management.ProjectRaster(in_raster=S2_band, out_raster=_area_name_S2_band_reproject_tif, out_coor_system="PROJCS[\"SWEREF99_TM\",GEOGCS[\"GCS_SWEREF99\",DATUM[\"D_SWEREF99\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",15.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", resampling_type="BILINEAR")
    _area_name_S2_band_reproject_tif = arcpy.Raster(_area_name_S2_band_reproject_tif)
    return _area_name_S2_band_reproject_tif


def clip_ortho(area_name, area_shp, ortho_path):
    """
    Clip the full 4-band orthophoto to the study area polygon.

    The clipped ortho (all bands intact) is kept as a single multi-band
    file and is used later as input to the Random Forest classifier.

    Parameters
    ----------
    area_name  : str  Glacier name
    area_shp   : str  Path to the single-area mask shapefile
    ortho_path : str  Path to the source orthophoto raster

    Returns
    -------
    arcpy.Raster  Clipped orthophoto raster object
    """
    _area_name_ortho_tif = arcpy.Raster(ortho_path)

    Output_raster = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_ortho_clip.tif"
    Extract_by_Mask_3_ = Output_raster
    Output_raster = arcpy.sa.ExtractByMask(_area_name_ortho_tif, area_shp, "INSIDE")
    Output_raster.save(Extract_by_Mask_3_)
    return Output_raster


def clip_ortho_band(area_name, area_shp, s2_reprojected_path, s2_fishnet_shp_path, s2_clipped_path, ortho_band_name, ortho_band_path):
    """
    Aggregate one orthophoto band to 10 m using S2 fishnet cells as zones.

    Steps:
      1. Zonal Statistics (MEAN) — for each 10 m fishnet cell, compute the
         average ortho pixel value (DN 0–255) across all high-res ortho pixels
         that fall within it. This downsamples the ~0.4 m ortho to 10 m while
         preserving the spatial alignment with S2 pixels.
      2. ExtractByMask — clip the 10 m result to the study area polygon.

    The snap raster ensures the 10 m output cells align exactly with S2 pixels.

    Parameters
    ----------
    area_name           : str  Glacier name
    area_shp            : str  Path to the single-area mask shapefile
    s2_reprojected_path : str  Reprojected S2 raster (used for snap alignment)
    s2_fishnet_shp_path : str  10 m fishnet polygon shapefile
    s2_clipped_path     : str  Clipped S2 band (used as snap raster for clipping)
    ortho_band_name     : str  Band identifier (e.g. 'Band_1')
    ortho_band_path     : str  Path to the ortho band raster

    Returns
    -------
    arcpy.Raster  10 m aggregated and clipped ortho band
    """
    arcpy.env.overwriteOutput = True
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    ortho_band = arcpy.Raster(ortho_band_path)

    # Aggregate ortho band to 10 m — one mean value per S2 fishnet cell
    _area_name_ortho_band_mean_10m_tif = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{ortho_band_name}_mean_10m.tif"
    Zonal_Statistics = _area_name_ortho_band_mean_10m_tif
    _area_name_ortho_band_mean_10m_tif = arcpy.sa.ZonalStatistics(s2_fishnet_shp_path, "FID", ortho_band, "MEAN", "DATA", "CURRENT_SLICE", 90, "AUTO_DETECT", "ARITHMETIC", 360)
    _area_name_ortho_band_mean_10m_tif.save(Zonal_Statistics)

    # Clip to study area boundary, snapping to S2 grid
    _area_name_ortho_band_mean_10m_clip_tif = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{ortho_band_name}_mean_10m_clip.tif"
    Extract_by_Mask = _area_name_ortho_band_mean_10m_clip_tif
    with arcpy.EnvManager(snapRaster=s2_clipped_path):
        _area_name_ortho_band_mean_10m_clip_tif = arcpy.sa.ExtractByMask(_area_name_ortho_band_mean_10m_tif, area_shp, "INSIDE", "DEFAULT")
        _area_name_ortho_band_mean_10m_clip_tif.save(Extract_by_Mask)

    return _area_name_ortho_band_mean_10m_clip_tif


def create_mask(area_name,
                clipped_s2_NIR_path,
                clipped_s2_Green_path,
                clipped_s2_SWIR_path,
                clipped_s2_SCL_path,
                clipped_ortho_Red_path,
                clipped_ortho_Green_path,
                clipped_ortho_Blue_path,
                ):
    """
    Build a pixel quality mask to exclude unreliable pixels from band calibration.

    Pixels are masked (excluded) if any of the following conditions are true:
      - Ortho brightness (R+G+B) < 205  → likely shadow or very dark surface
      - S2 SCL class == 2              → cloud shadow (per S2 scene classification)
      - NDWI > -0.01                   → likely water (Green-NIR)/(Green+NIR)
      - NDSI > 0                       → likely snow  (Green-SWIR)/(Green+SWIR)

    The resulting mask (1=masked, 0=valid) is then inverted so that:
      - Valid pixels retain value 1
      - Masked pixels become NoData
    This inverted mask is used with ExtractByMask to keep only valid pixels
    for the OLS band correlation.

    Parameters
    ----------
    area_name              : str  Glacier name
    clipped_s2_NIR_path    : str  Clipped S2 NIR band path
    clipped_s2_Green_path  : str  Clipped S2 Green band path
    clipped_s2_SWIR_path   : str  Clipped S2 SWIR band path
    clipped_s2_SCL_path    : str  Clipped S2 Scene Classification Layer path
    clipped_ortho_Red_path : str  Clipped 10 m aggregated ortho Red band path
    clipped_ortho_Green_path: str Clipped 10 m aggregated ortho Green band path
    clipped_ortho_Blue_path: str  Clipped 10 m aggregated ortho Blue band path

    Returns
    -------
    str  Path to the inverted mask raster (valid pixels = 1, masked = NoData)
    """
    arcpy.env.overwriteOutput = True
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")

    s2_NIR = arcpy.Raster(clipped_s2_NIR_path)
    s2_SWIR = arcpy.Raster(clipped_s2_SWIR_path)
    s2_Green = arcpy.Raster(clipped_s2_Green_path)
    s2_SCL = arcpy.Raster(clipped_s2_SCL_path)

    # Sum of ortho R+G+B bands (each 0–255); low values indicate shadowed pixels
    ortho_brightness_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_ortho_brightness.tif"
    with arcpy.EnvManager(snapRaster=clipped_s2_NIR_path):
        ortho_brightness = Raster(clipped_ortho_Red_path) + Raster(clipped_ortho_Green_path) + Raster(clipped_ortho_Blue_path)
        ortho_brightness.save(ortho_brightness_output_path)

    # NDWI = (Green - NIR) / (Green + NIR) — positive values indicate water
    NDWI_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_NDWI.tif"
    with arcpy.EnvManager(snapRaster=clipped_s2_NIR_path):
        NDWI = (s2_Green - s2_NIR) / (s2_Green + s2_NIR)
        NDWI.save(NDWI_output_path)

    # Resample S2 Green (10 m) to 20 m to match SWIR band resolution for NDSI
    s2_green_20m_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_s2_b3_20m.tif"
    with arcpy.EnvManager(snapRaster=clipped_s2_SWIR_path):
        arcpy.management.Resample(
            in_raster=s2_Green,
            out_raster=s2_green_20m_output_path,
            resampling_type="BILINEAR",
            cell_size=20
        )
        s2_green_20m = arcpy.Raster(s2_green_20m_output_path)

    # NDSI = (Green - SWIR) / (Green + SWIR) — positive values indicate snow
    NDSI_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_NDSI.tif"
    with arcpy.EnvManager(snapRaster=clipped_s2_SWIR_path):
        # Con ensures no division by zero
        NDSI = Con(
            (~IsNull(s2_green_20m)) &
            (~IsNull(s2_SWIR)) &
            ((Float(s2_green_20m) + Float(s2_SWIR)) != 0),
            (Float(s2_green_20m) - Float(s2_SWIR)) / (Float(s2_green_20m) + Float(s2_SWIR))
        )
        NDSI.save(NDSI_output_path)

    # Resample NDSI from 20 m back to 10 m to match NIR/Green resolution
    NDSI_10m_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_NDSI_10m.tif"
    with arcpy.EnvManager(snapRaster=clipped_s2_NIR_path):
        arcpy.management.Resample(
            in_raster=NDSI_output_path,
            out_raster=NDSI_10m_output_path,
            resampling_type="BILINEAR",
            cell_size=10
        )
        NDSI_10m = arcpy.Raster(NDSI_10m_output_path)

    # Resample SCL from 20 m to 10 m for use in the mask
    SCL_10m_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_SCL_10m.tif"
    with arcpy.EnvManager(snapRaster=clipped_s2_NIR_path):
        arcpy.management.Resample(
            in_raster=clipped_s2_SCL_path,
            out_raster=SCL_10m_output_path,
            resampling_type="BILINEAR",
            cell_size=10
        )
        SCL_10m = arcpy.Raster(SCL_10m_output_path)

    # Combine all exclusion criteria: 1 = masked (bad pixel), 0 = valid
    mask_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_mask.tif"
    with arcpy.EnvManager(snapRaster=clipped_s2_NIR_path):
        mask = Con(
            (ortho_brightness < 205) |   # dark/shadowed ortho pixel
            (SCL_10m == 2) |             # S2 cloud shadow class
            (NDWI > -0.01) |             # water
            (NDSI_10m > 0),              # snow
            1, 0
        )
        mask.save(mask_output_path)

    # Invert: remap 0 (valid) → 1, 1 (masked) → NoData
    # After inversion, ExtractByMask will keep only valid pixels
    mask_inv_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_mask_inv.tif"
    with arcpy.EnvManager():
        mask_inv = arcpy.sa.Reclassify(
            mask_output_path, "Value", "0 1;1 NODATA", "DATA"
        )
        mask_inv.save(mask_inv_output_path)

    return mask_inv_output_path


def band_correlation(
        area_name,
        area_shp_path,
        S2_fishnet_shp,
        mask_inv_output_path,
        s2_band_path,
        s2_band_name,
        selected_ortho_band_path,
        selected_ortho_band_name
):
    """
    Compute OLS regression coefficients between a normalised ortho band and S2 band.

    Steps:
      1. Apply the quality mask to both the ortho 10 m band and the S2 band
      2. Normalise each:
           ortho: DN / 255  → range 0–1
           S2:    (DN - 1000) / 10000  → surface reflectance (L2A offset correction)
      3. Sample both at S2 fishnet centroids (one sample per 10 m cell)
      4. Remove any samples with NoData in either band
      5. Run OLS: S2_reflectance = k * ortho_normalised + m
         (dependent = S2, explanatory = ortho)

    The resulting slope (k) and intercept (m) allow the ortho to be converted
    to pseudo-reflectance values comparable to S2 in Calibration_NDVI.py.

    Parameters
    ----------
    area_name                  : str  Glacier name
    area_shp_path              : str  Path to single-area shapefile (unused in OLS but kept for tracing)
    S2_fishnet_shp             : str  10 m fishnet shapefile for sampling
    mask_inv_output_path       : str  Inverted mask raster (valid = 1, bad = NoData)
    s2_band_path               : str  Clipped S2 band path
    s2_band_name               : str  S2 band identifier (e.g. 's2_b8')
    selected_ortho_band_path   : str  Clipped 10 m aggregated ortho band path
    selected_ortho_band_name   : str  Ortho band identifier (e.g. 'Band_4')

    Returns
    -------
    dict  Keys: area, s2_band, ortho_band, intercept, slope, and their standard
          errors and p-values from the OLS output table.
    """
    s2_band = arcpy.Raster(s2_band_path)

    # Apply quality mask to ortho band
    ortho_band_10m_mask_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_ortho_{selected_ortho_band_name}_10m_mask.tif"
    with arcpy.EnvManager(snapRaster=s2_band_path):
        ortho_band_10m_mask = arcpy.sa.ExtractByMask(
            selected_ortho_band_path, mask_inv_output_path, "INSIDE"
        )
        ortho_band_10m_mask.save(ortho_band_10m_mask_output_path)

    # Normalise ortho band: DN (0–255) → fractional reflectance (0–1)
    band_ortho_normalize_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{selected_ortho_band_name}_ortho_normalize.tif"
    with arcpy.EnvManager(snapRaster=s2_band_path):
        band_ortho_normalize = ortho_band_10m_mask / 255
        band_ortho_normalize.save(band_ortho_normalize_output_path)

    # Apply quality mask to S2 band
    S2_band_mask_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{s2_band_name}_mask.tif"
    with arcpy.EnvManager(snapRaster=s2_band_path):
        S2_Band_mask = arcpy.sa.ExtractByMask(
            s2_band, mask_inv_output_path, "INSIDE",
        )
        S2_Band_mask.save(S2_band_mask_output_path)

    # Normalise S2 band: subtract L2A offset (1000) and divide by 10000
    # → converts integer DN to surface reflectance (0–1 range)
    S2_band_normalize_output_path = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{s2_band_name}_normalize.tif"
    with arcpy.EnvManager(snapRaster=s2_band_path):
        S2_band_normalize = (S2_Band_mask - 1000) / 10000
        S2_band_normalize.save(S2_band_normalize_output_path)

    # Sample both normalised rasters at the S2 fishnet cell centroids
    Sample_band_shp = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_Sample_{selected_ortho_band_name}.shp"
    arcpy.sa.Sample(
        [band_ortho_normalize_output_path, S2_band_normalize_output_path],
        S2_fishnet_shp,
        Sample_band_shp,
        "NEAREST", "FID", "CURRENT_SLICE", [], "", None, "",
        "ROW_WISE", "FEATURE_CLASS"
    )

    # Identify sample points where either band has NoData (-9999)
    sample_select_shp = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_sample_select.shp"
    arcpy.analysis.Select(
        in_features=Sample_band_shp,
        out_feature_class=sample_select_shp,
        where_clause="v_raster_1 = -9999 Or v_raster_2 = -9999"
    )

    # Remove NoData points from the sample before running OLS
    Sample_Band_Erase_shp = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_Sample_{selected_ortho_band_name}_Erase.shp"
    arcpy.analysis.Erase(
        in_features=Sample_band_shp,
        erase_features=sample_select_shp,
        out_feature_class=Sample_Band_Erase_shp
    )

    # OLS: S2_reflectance (v_raster_2) ~ ortho_normalised (v_raster_1)
    # Output includes coefficient table (.dbf) with slope, intercept, p-values
    Band_OLS_shp = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{selected_ortho_band_name}_OLS.shp"
    Band_OLS_pdf = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{selected_ortho_band_name}_OLS.pdf"
    Band_OLS_coeff_table = f"C:\\TEMP\\Vanessa_Henriksson\\Data\\Python\\Outputs\\{area_name}\\{area_name}_{selected_ortho_band_name}_OLS_coeff_temp.dbf"
    arcpy.stats.OrdinaryLeastSquares(
        Input_Feature_Class=Sample_Band_Erase_shp,
        Unique_ID_Field="FID_",
        Output_Feature_Class=Band_OLS_shp,
        Dependent_Variable="v_raster_2",
        Explanatory_Variables=["v_raster_1"],
        Coefficient_Output_Table=Band_OLS_coeff_table,
        Diagnostic_Output_Table="",
        Output_Report_File=Band_OLS_pdf
    )

    # Read the coefficient table and return as a dictionary
    coeff_rows = {}
    with arcpy.da.SearchCursor(Band_OLS_coeff_table, ["Variable", "Coef", "StdError", "t_Stat", "Prob"]) as cursor:
        for row in cursor:
            coeff_rows[row[0]] = {"Coef": row[1], "StdError": row[2], "t_Stat": row[3], "Prob": row[4]}
    arcpy.management.Delete(Band_OLS_coeff_table)

    intercept = coeff_rows.get("Intercept", {})
    slope = coeff_rows.get("v_raster_1", {})
    result = {
        "area": area_name,
        "s2_band": s2_band_name,
        "ortho_band": selected_ortho_band_name,
        "intercept": intercept.get("Coef"),
        "intercept_std_err": intercept.get("StdError"),
        "intercept_p": intercept.get("Prob"),
        "slope": slope.get("Coef"),
        "slope_std_err": slope.get("StdError"),
        "slope_p": slope.get("Prob"),
    }

    print(f"NIR model processing complete for {area_name}!")
    return result
